version: '3.6'
services:
  hasura-auth:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - '4000:4000'
    volumes:
      - ./email-templates:/app/email-templates